a=int(input("Enter 1st number:"))
b=int(input("Enter 2nd number:"))
print("Addition:",a+b)
print("Substraction:",a-b)
print("Multiplication:",a*b)
print("Division:",a/b)
print("Modulus:",a%b)
print("Power:",a**b)